
#define PI 3.14159265358979

struct JONSWAP_parameters
{
    float scale;
    float angle;
    float spreadBlend;
    float swell;
    float alpha;
    float peakOmega;
    float gamma;
    float shortWavesFade;
};

StructuredBuffer<JONSWAP_parameters> _JonswapParameters : register(t0); //VS编辑器对于计算着色器的联想支持极差，没有提示很正常

cbuffer FFTOceanParams : register(b0)
{
    float _Depth;
    float _Gravity;
    float _FrameTime;
    float _RepeatTime;
    float _LowCutOff;
    float _HighCutOff;
    float _WaveSharpX;
    float _WaveSharpY;
    int _Resolution;
    int _LengthScale0;
    int _LengthScale1;
    int _LengthScale2;
    int _LengthScale3;
    int _Seed;
    float _FoamBias;
    float _FoamPower;
    float _FoamAdd;
    float _FoamDecayRate;
    
    uint _InitialSpectrumIndex;
    uint _SpectrumIndex;
    uint _DisplacementIndex;
    uint _SlopeIndex;
    float _Padding[2];
};

RWTexture2D<float4> _InitializeSpectrumTex : register(u0); //为什么这里填的是float，不是填类型吗，我还以为要填InitializeSpectrumTex
RWTexture2D<float4> _SpectrumTex01 : register(u1);
RWTexture2D<float4> _SpectrumTex02 : register(u2);
RWTexture2D<float4> _VariationMask : register(u3);
RWTexture2D<float4> _DisplacementTex : register(u4);
RWTexture2D<float2> _SlopeTex : register(u5);
RWTexture2D<float> _BuoyancyData : register(u6);

float2 EnlerFormula(float x)
{
    return float2(cos(x), sin(x));

}

float2 ComplexMul(float2 a, float2 b)
{
    return float2(a.x * b.x - a.y * b.y, a.x * b.y + a.y * b.x);
}

//Random Number Generator-hash (需要寻找依据)a
float hash(uint n)
{
    n = (n << 13U) ^ n; //这是什么雷霆语法？
    n = n * (n * n * 15731U + 0x789221U) + 0x1376312589Ul;
    return float(n & uint(0x7fffffffU)) / float(0x7fffffff);
}

//用Box-Muller转换为高斯随机数
float2 gaussian(float u1, float u2)
{
    //u1&u2 are two random numbers generated by hash function
    float R = sqrt(-2 * log(u1));
    float theta = 2 * PI * u2;
    
    return float2(R * cos(theta), R * sin(theta));
}

//Dispersion 波浪的色散关系(用来计算omega)
float Dispersion (float k)
{
    return sqrt(_Gravity * k * tanh(min(k * _Depth, 20)));
}

//把连续频谱能量换算成离散 FFT bin 时的修正系数
float DispersionDerivative(float kMag)
{
    float tanH = tanh(min(kMag * _Depth, 20));
    float cosH = cosh(kMag * _Depth);
    return _Gravity * (_Depth * kMag / cosH / cosH + tanH) / Dispersion(kMag) / 2.0f;
}

//浅水修正
float TMACorrection(float omega)
{
    float omegaH = omega * sqrt(_Depth / _Gravity);
    if(omegaH <= 1.0f)
        return 0.5f * omegaH * omegaH;
    if(omegaH < 2.0f)
        return 1.0f - 0.5f * (2.0f - omegaH) * (2.0f - omegaH);
    return 1.0f;
}

float JONSWAP(float omega, JONSWAP_parameters parameters)
{
    float sigma = (omega <= parameters.peakOmega) ? 0.07f : 0.09f;
    float r = exp(-(omega - parameters.peakOmega) * (omega - parameters.peakOmega) / 2.0f / sigma / sigma / parameters.peakOmega / parameters.peakOmega);
    float oneOverOmega = 1.0f / omega;
    float peakOmegaOverOmega = parameters.peakOmega / omega;
    
    float Sw = parameters.scale * TMACorrection(omega)
        * parameters.alpha * _Gravity * _Gravity
        * oneOverOmega * oneOverOmega * oneOverOmega * oneOverOmega * oneOverOmega
        * exp(-1.25f * peakOmegaOverOmega * peakOmegaOverOmega * peakOmegaOverOmega * peakOmegaOverOmega)
        * pow(abs(parameters.gamma), r);
    
    return Sw;
}

//归一化常数：一个四次多项式拟合
float NormalizationFactor(float s)
{
    float s2 = s * s;
    float s3 = s2 * s;
    float s4 = s3 * s;
    if(s < 5)
        return -0.000564f * s4 + 0.00776f * s3 - 0.044f * s2 + 0.192f * s + 0.163f;
    else
        return -4.80e-08f * s4 + 1.07e-05f * s3 - 9.53e-04f * s2 + 5.90e-02f * s + 3.93e-01f;
}

//让波浪能量集中在风向附近，s 越大越集中（高频集中、低频发散）
float Cosine2s(float theta, float s)
{
    return NormalizationFactor(s) * pow(abs(cos(0.5f * theta)), 2.0f * s);
}

//扩散指数
float SpreadPower(float omega, float peakOmega)
{
    float ratio = abs(omega / peakOmega);
    if(omega <= peakOmega)
        return 6.97f * pow(ratio, 5.0f);
    else
        return 9.77f * pow(ratio, -2.5f);
}

//在两种方向分布模型之间平滑过渡（纯重力波 vs. 风驱波）
float DirectionSpectrum(float theta, float omega, JONSWAP_parameters parameters)
{
    float s = SpreadPower(omega, parameters.peakOmega) 
        + 16 * tanh(min(omega / parameters.peakOmega, 20)) * parameters.swell * parameters.swell;
    return lerp(2.0f * PI * cos(theta) * cos(theta), 
        Cosine2s(theta - parameters.angle, s), parameters.spreadBlend);
}

//高频衰减
float ShortWaveFade(float kLength, JONSWAP_parameters parameters)
{
    return exp(-parameters.shortWavesFade * parameters.shortWavesFade * kLength * kLength / 10000);
}

[numthreads(8, 8, 1)] 
void CS(uint3 id : SV_DispatchThreadID) //InitializeSpectrumTex
//DispatchThreadID获取的是当前线程在全局里面的编号
{
    float seed = id.x + id.y * _Resolution + _Resolution;
    seed += _Seed;
    
    float LengthScale[] = { _LengthScale0, _LengthScale1, _LengthScale2, _LengthScale3 };
    
    {
        float halfN = _Resolution / 2.0f; //获取纹理中心坐标
        float deltaK = 2.0f * PI / LengthScale[_InitialSpectrumIndex]; //像素单位之间的频率差
        float2 k = (id.xy - halfN) * deltaK;
        float kLength = length(k);
        
        seed += _InitialSpectrumIndex + hash(seed) * 10;
        float2 gauss1 = gaussian(hash(seed), hash(seed * 2));
        float2 gauss2 = gaussian(hash(seed * 3), hash(seed * 4));

        if(_LowCutOff <= kLength && kLength <= _HighCutOff)
        {
            float omega = Dispersion(kLength);
            float kAngle = atan2(k.y, k.x);
            
            float dOmegadk = DispersionDerivative(kLength);
            
            float JONSpectrum = JONSWAP(omega, _JonswapParameters[_InitialSpectrumIndex * 2])
                * DirectionSpectrum(kAngle, omega, _JonswapParameters[_InitialSpectrumIndex * 2])
                * ShortWaveFade(kLength, _JonswapParameters[_InitialSpectrumIndex * 2]);
                
            if (_JonswapParameters[2 * _InitialSpectrumIndex + 1].scale > 0)
            {
                JONSpectrum += JONSWAP(omega, _JonswapParameters[_InitialSpectrumIndex * 2 + 1])
                    * DirectionSpectrum(kAngle, omega, _JonswapParameters[_InitialSpectrumIndex * 2 + 1])
                    * ShortWaveFade(kLength, _JonswapParameters[_InitialSpectrumIndex * 2 + 1]);
            }
            float2 H0 = float2(gauss1.x, gauss2.y) * sqrt(JONSpectrum * 2 * abs(dOmegadk) / kLength * deltaK * deltaK);
            _InitializeSpectrumTex[id.xy] = float4(H0, 0, 0);
        }
        else
        {
            _InitializeSpectrumTex[id.xy] = 0.0f;
        }
    }
}

[numthreads(8, 8, 1)]
void CS_PackSpectrumConjugate(uint3 id : SV_DispatchThreadID)
{
    //四套不同的初始化频谱就要靠C++端手动配置了
    float2 h0 = _InitializeSpectrumTex[uint2(id.xy)].rg;
    float2 h0conju = _InitializeSpectrumTex[uint2((_Resolution - id.x) % _Resolution, (_Resolution - id.y) % _Resolution)];
    
    _InitializeSpectrumTex[uint2(id.xy)] = float4(h0, h0conju.x, -h0conju.y);
}

[numthreads(8, 8, 1)]
void CS_UpdateSpectrum(uint3 id : SV_DispatchThreadID)
{
    float LengthScale[] = { _LengthScale0, _LengthScale1, _LengthScale2, _LengthScale3 };
    
    float4 Initial = _InitializeSpectrumTex[uint2(id.xy)];
    float2 h0 = Initial.xy;
    float2 h0conju = Initial.zw;
    
    float halfResolution = _Resolution / 2.0f;
    float2 k = (id.xy - halfResolution) * 2.0f * PI / LengthScale[_InitialSpectrumIndex];
    float kLength = length(k);
    float kLengthRcp = rcp(kLength);
    
    if(kLength < 0.0001f)
    {
        kLengthRcp = 1.0f;
    }

    float w0 = 2.0f * PI / _RepeatTime;
    float dispersion = floor(sqrt(_Gravity * kLength) / w0) * w0 * _FrameTime; //在 _FrameTime 这段时间内，该频率分量累积的相位变化量（单位弧度）
    
    float2 exponent = EnlerFormula(dispersion);
    
    float2 htime = ComplexMul(h0, exponent) + ComplexMul(h0conju, float2(exponent.x, -exponent.y));
    float2 ihtime = float2(-htime.y, htime.x);
    
    float2 displacementX = ihtime * k.x * kLengthRcp;
    float2 displacementY = htime;
    float2 displacementZ = ihtime * k.y * kLengthRcp;
    
    float2 displacementX_dx = -htime * k.x * k.x * kLengthRcp;
    float2 displacementY_dx = ihtime * k.x;
    
    float2 displacementY_dz = k.y * ihtime;
    float2 displacementZ_dz = -htime * k.y * k.y * kLengthRcp;
    
    float2 displacementZ_dx = -htime * k.y * k.y * kLengthRcp;
    
    float2 htimeDisplacementX = float2(displacementX.x - displacementZ.y, displacementX.y + displacementZ.x);
    float2 htimeDisplacementZ = float2(displacementY.x - displacementZ_dx.y, displacementY.y + displacementZ_dx.x);
    
    float2 htimeSlopeX = float2(displacementY_dx.x - displacementY_dz.y, displacementY_dx.y + displacementY_dz.x);
    float2 htimeSlopeZ = float2(displacementX_dx.x - displacementZ_dz.y, displacementX_dx.y + displacementZ_dz.x);
    
    _SpectrumTex01[uint2(id.xy)] = float4(htimeDisplacementX, htimeDisplacementZ);
    _SpectrumTex02[uint2(id.xy)] = float4(htimeSlopeX, htimeSlopeZ);
    
    if(_InitialSpectrumIndex)
    {
        _VariationMask[uint2(id.xy)] = float4(_InitializeSpectrumTex[id.xy].x, 0.0f, 0.0f, 0.0f);
    }
}

[numthreads(1, 1024, 1)]
void CS_HorizontalIFFT(uint3 id : SV_DispatchThreadID)
{
    
}

[numthreads(1024, 1, 1)]
void CS_VerticalIFFT(uint3 id : SV_DispatchThreadID)
{
    
}

[numthreads(8, 8, 1)]
void CS_AssembleTextures(uint3 DTid : SV_DispatchThreadID)
{
    
}